### ISSUE TITLE
Response data corruption

### ISSUE THREAD

**Issue by jitsni** [reaktivity/nukleus-http.java#59]
Response data is getting corrupted some times. It seems to be related with the connection getting used for multiple requests/responses.

* When -Dnukleus.http.maximum.connections=1 specified, the response data is not getting corrupted.

* Also, the following is observed (the line numbers may be off a bit):
```
java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.base/java.util.BitSet.clear(BitSet.java:541)
	at org.reaktivity.reaktor.internal.buffer.DefaultBufferPool.release(DefaultBufferPool.java:136)
	at org.reaktivity.reaktor.internal.buffer.CountingBufferPool.release(CountingBufferPool.java:84)
	at org.reaktivity.nukleus.http.internal.stream.ClientConnectReplyStream.decodeBufferedData(ClientConnectReplyStream.java:482)
	at org.reaktivity.nukleus.http.internal.stream.ClientConnectReplyStream.handleWindow(ClientConnectReplyStream.java:962)
	at org.reaktivity.nukleus.http.internal.stream.ClientConnectReplyStream.handleThrottleAfterBegin(ClientConnectReplyStream.java:942)
	at org.reaktivity.nukleus.http.internal.stream.ClientConnectReplyStream.handleThrottle(ClientConnectReplyStream.java:911)
	at org.reaktivity.reaktor.internal.acceptable.Target.handleRead(Target.java:157)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
	at org.reaktivity.reaktor.internal.acceptable.Target.process(Target.java:69)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.reaktor.Reaktor.lambda$supplyWorker$0(Reaktor.java:180)
	at org.reaktivity.reaktor.Reaktor$1.doWork(Reaktor.java:116)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
I think this can be fixed by using   s/factory.bufferPool.release(slotIndex)/releaseSlotIfNecessary()

* There is a slot remaining (slotIndex != NO_SLOT) in httpResponseBegin() sometimes. Is this ok  since responses are not pipelined ?

**Comment by cmebarrow** [comment]
@jitsni  httpResponseBegin is called from the decoding states, so there could be a slot remaining in httpResponseBegin if caller of the decodingstate is decodeBufferedData.

**Comment by cmebarrow** [comment]
The call stack can only be happening because handleInvalidResponseAndReset() gets called from one of the decoders which is called from decodeBufferedData. That would be due to some aspect of the http response which we think is incorrect or which we cannot handle (e.g. transfer-encoding other than chunked).

**Comment by jfallows** [comment]
No longer reproducible.
